### ISSUE TITLE
[Perception] Test RTAB-Map Binaries on Jetson Nano

### ISSUE THREAD

**Issue by ttchalakov** [IllinoisRoboticsInSpace/IRIS#10]
The switch from compiling RTAB-Map from source to using the binaries available through `apt` did not include testing RTAB-Map on the Jetson Nano. 
Steps to test RTAB-Map on the Jetson Nano:
1. Download and flash one of the 128GB SD Cards with the [Ubuntu_20_L4T_3243_OpenCV_420.zip](https://uofi.app.box.com/folder/222425768858) image. This image has OpenCV 4.2.0 with CUDA compiled and installed on it, but the IRIS repo's dependencies have not been installed.
2. Plug in the SD card into the Jetson Nano, navigate to the IRIS repo in `~/colcon_ws/src/IRIS`, switch the branch to master and pull the latest changes (should wait until this pull request #9 is merged).
3. Go into the `/install_scripts` folder, run the `install_jetson_deps.sh` script, and reboot the Jetson Nano.
4. Plug in the realsense camera and run RTAB-Map using the commands in the repo's README.

**Comment by gxywang** [comment]
works; updated launch command to match `realsense_ros`'s for `unite_imu_method` and added `queue_size` param. very slow right now though
